require("logic.classLoader")
love.graphics.setBackgroundColor(200, 200, 200)
love.graphics.setDefaultFilter("nearest", "nearest", 1)
MathHelper = MathHelper()
MusicHandler = MusicHandler()
UI = UI()
Renderer = Renderer()
State = State()
Player = Player(100, 1024, Sprite("test.tga", 16, 16, 1, 4))
Player.sprite:setRotationSpeed(11)
Driver()
