require("items.item")
require("items.itemBox")
require("items.nullItem")
require("items.passiveItem")
require("items.activeItem")
require("items.shieldActive")
require("items.extraLifePassive")
require("items.movingTurretPassive")
require("items.damageBoostActive")
require("items.blackHoleActive")
require("items.bombPassive")
return require("items.itemPool")
