require("utils.utilsLoader")
require("ui.uiLoader")
require("logic.gameObject")
require("logic.player")
require("enemies.enemyLoader")
require("projectiles.projectileLoader")
require("turrets.turretLoader")
require("objectives.objectiveLoader")
require("logic.driver")
return require("screens.screenLoader")
