local queue = { }
table.insert(queue, "utils.utilsLoader")
table.insert(queue, "ui.uiLoader")
table.insert(queue, "logic.gameObject")
table.insert(queue, "logic.player")
table.insert(queue, "enemies.enemyLoader")
table.insert(queue, "projectiles.projectileLoader")
table.insert(queue, "turrets.turretLoader")
table.insert(queue, "bosses.bossLoader")
table.insert(queue, "objectives.objectiveLoader")
table.insert(queue, "particles.particleLoader")
table.insert(queue, "maps.mapLoader")
table.insert(queue, "screens.screenLoader")
table.insert(queue, "logic.driver")
return queue
