require("objectives.attackGoal")
require("objectives.defendGoal")
require("objectives.findGoal")
require("objectives.captureGoal")
require("objectives.mode")
require("objectives.wave")
require("objectives.eliminationMode")
require("objectives.attackMode")
require("objectives.defendMode")
require("objectives.darkMode")
require("objectives.captureMode")
require("objectives.eliminationWave")
require("objectives.attackWave")
require("objectives.defendWave")
require("objectives.darkWave")
require("objectives.captureWave")
return require("objectives.objectives")
