require("objectives.attackGoal")
require("objectives.defendGoal")
require("objectives.mode")
require("objectives.wave")
require("objectives.eliminationMode")
require("objectives.attackMode")
require("objectives.eliminationWave")
require("objectives.attackWave")
return require("objectives.objectives")
