require("objectives.attackGoal")
require("objectives.defendGoal")
require("objectives.mode")
require("objectives.wave")
require("objectives.eliminationMode")
require("objectives.attackMode")
require("objectives.defendMode")
require("objectives.eliminationWave")
require("objectives.attackWave")
require("objectives.defendWave")
return require("objectives.objectives")
